name: Petiquette
title: Petiquette
description: >
  Articles relating to dogs.
baseurl: ""
url: "https://petiquette.dog"

theme: jekyll-theme-architect
timezone: America/Los_Angeles
permalink: pretty
